name: Node.js Workflow

on:
  push:
    branches:
      - main

jobs:
  linting-and-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setting up the Node environment
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install all the dependencies
      run: npm install

    - name: Run Lint
      run: npm run lint

    - name: Run unit Tests using zest
      run: npm test
